/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/As-Caida/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/P2p-Gnutella31/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Email-EuAll/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Soc-Slashdot0922/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Web-NotreDame/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Com-Dblp/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Amazon0601/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/RoadNet-CA/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Wiki-Talk/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Web-BerkStan/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/As-Skitter/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Cit-Patents/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Soc-Pokec/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Sx-Stackoverflow/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Com-Lj/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Soc-LiveJ/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Com-Orkut/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Twitter7/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/TRUST-new/trust-new /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/Com-Friendster/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s19-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s19-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s19-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s19-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s19-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s19-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s19-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s19-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s21-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s21-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s21-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s21-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s21-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s21-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s21-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s21-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s23-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s23-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s23-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s23-e8/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s23-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s23-e32/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s23-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s23-e128/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s18-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s18-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s20-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s20-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s22-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s22-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s24-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s24-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s26-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s26-e2/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e4/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e4/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e16/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e16/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e64/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e64/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e256/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e256/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster0-s17-e1024/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/trust-new/trust /home/LiJB/cuda_project/TC-compare-V100/data/trust_dataset/cluster3-s17-e1024/  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/trust-new/time_output.txt