/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/As-Caida/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/P2p-Gnutella31/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Email-EuAll/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Soc-Slashdot0922/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Web-NotreDame/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Com-Dblp/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Amazon0601/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/RoadNet-CA/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Wiki-Talk/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Web-BerkStan/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/As-Skitter/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Cit-Patents/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Soc-Pokec/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Sx-Stackoverflow/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Com-Lj/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Soc-LiveJ/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Com-Orkut/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Twitter7/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
/home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/Com-Friendster/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s19-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s19-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s19-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s19-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s19-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s19-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s19-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s19-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s21-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s21-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s21-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s21-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s21-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s21-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s21-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s21-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s23-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s23-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s23-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s23-e8/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s23-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s23-e32/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s23-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s23-e128/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s18-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s18-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s20-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s20-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s22-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s22-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s24-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s24-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s26-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s26-e2/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e4/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e4/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e16/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e16/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e64/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e64/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e256/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e256/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster0-s17-e1024/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt
# /home/LiJB/cuda_project/TC-compare-V100/approach/polak/polak  /home/LiJB/cuda_project/TC-compare-V100/data/polak_dataset/cluster3-s17-e1024/edges.bin  0  100 >>  /home/LiJB/cuda_project/TC-compare-V100/log/polak/time_output.txt